databases:
  - name: gram-bazaar-db
    databaseName: gram_bazaar
    user: gram_user
    plan: free
    region: singapore

services:
  # 1. The Backend (FastAPI)
  - type: web
    name: gram-bazaar-backend
    env: docker
    plan: free
    region: singapore
    rootDir: .
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gram-bazaar-db
          property: connectionString
      - key: PORT
        value: "8000"
    # startCommand removed (It will use CMD from Dockerfile)

  # 2. The Frontend (Streamlit)
  - type: web
    name: gram-bazaar-frontend
    env: docker
    plan: free
    region: singapore
    rootDir: .
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: http://gram-bazaar-backend:8000
      - key: PORT
        value: "8501"
    # startCommand removed (It will use CMD from Dockerfile)